<?php
$site = $this->serverUrl();
$dom = new DomDocument("1.0", "UTF-8");
$sitemap = $dom->createElement('configdata');
$nav = $dom->createElement('locations');
$news = $dom->createElement('database');
$sitemap->appendChild($nav);
$news->appendChild($dom->createElement('uri', $this->serverUrl() . '/database/sitemap/images/'));
$nav->appendChild($news);
$pages = $dom->createElement('pages');
$search = new Pas_Solr_Handler();
$search->setCore('images');
$params['start'] = 0;
$params['show'] = 1000;
$params['format'] = 'sitemap';
$search->setParams($params);
$search->execute();
$paginate = $search->createPagination();
$a = ceil($paginate->getTotalItemCount() / $paginate->getItemCountPerPage());
for ($i = 1; $i <= $a; $i++) {
    $story = $dom->createElement('page' . $i);
    $story->appendChild($dom->createElement('label', 'Scheme images page ' . $i));
    $story->appendChild($dom->createElement('uri', $this->serverUrl() . '/sitemap/images/page/' . $i));
    $pages->appendChild($story);
}
$news->appendChild($pages);
$dom->appendChild($sitemap);
$xmlData = $dom->saveXML();
echo $xmlData;